Public Class RptAppraisalVE

    Private Sub Rpt_BeforePrint(sender As Object, e As Printing.PrintEventArgs) Handles MyBase.BeforePrint
        'USER INTERFACE
        If AllowStandardUI = False Then
            Exit Sub
        End If
        ReportLabelWithBackgroundFontSettings({XrLabel6, XrLabel9})
        ReportLabelFontSettings({XrLabel4, lblDate, XrLabel3, lblAppaiseNum, XrLabel5, lblAppraiseFor, XrLabel22, lblAppraisedBy, XrLabel7, lblMake, XrLabel13, lblPlateNumber, XrLabel23, lblMotorNumber, XrLabel29, lblORNumber, XrLabel8, lblType, XrLabel15, lblTransmission, XrLabel19, lblGasoline, XrLabel25, lblSerialNumber, XrLabel33, lblGrossWeight, XrLabel18, lblRim, XrLabel11, lblEngine, XrLabel17, lblBodyColor, XrLabel20, lblYear, XrLabel27, lblRegCertNumber, XrLabel31, lblMileAge, XrLabel10, XrLabel12, XrLabel14, XrLabel16, XrLabel28, XrLabel39, XrLabel43, XrLabel51, XrLabel55, XrLabel63, XrLabel67, XrLabel75, XrLabel79, XrLabel86, XrLabel88, XrLabel94, XrLabel96, txtEngine, txtSteering, txtClutch, txtHeadLight, txtSignalLight, txtShock, txtUnderchassis, txtUpholstery, txtTempGauge, txtOdometer, txtAppraisersRemarks, txtSource, txtMarketValue, txtAppraisedValue, XrLabel21, XrLabel32, XrLabel38, XrLabel45, XrLabel50, XrLabel57, XrLabel62, XrLabel69, XrLabel74, XrLabel81, XrLabel90, txtTransmission, dTires, txtTires, txtAcceleration, txtParkLight, txtHorn, txtChassis, txtFrontBumper, txtAmpheres, txtFuel, txtStarter, txtTelNo, lblLoanable, txtLoanble, txtLoanableP, XrLabel24, XrLabel35, XrLabel42, XrLabel47, XrLabel54, XrLabel59, XrLabel66, XrLabel71, XrLabel78, XrLabel83, XrLabel92, txtDifferential, txtBrakes, txtWiper, txtBackUp, txtSideMirror, txtBodyFlooring, txtRearBumper, txtOilPressure, txtSpeedometer, txtBodyPaint, txtSellingPrice})
        ReportCheckBoxFontSettings({cbxEngine_G, cbxSteering_G, cbxClutch_G, cbxHeadLight_G, cbxSignalLight_G, cbxShock_G, cbxUnderchassis_G, cbxUpholstery_G, cbxTempGauge_G, cbxOdometer_G, cbxTransmission_G, cbxAcceleration_G, cbxParkLight_G, cbxHorn_G, cbxChassis_G, cbxFrontBumper_G, cbxAmpheres_G, cbxFuel_G, cbxStarter_G, cbxDifferential_G, cbxBrakes_G, cbxWiper_G, cbxBackUp_G, cbxSideMirror_G, cbxBodyFlooring_G, cbxRearBumper_G, cbxOilPressure_G, cbxSpeedometer_G, cbxBodyPaint_G, cbxEngine_F, cbxSteering_F, cbxClutch_F, cbxHeadLight_F, cbxSignalLight_F, cbxShock_F, cbxUnderchassis_F, cbxUpholstery_F, cbxTempGauge_F, cbxOdometer_F, cbxTransmission_F, cbxAcceleration_F, cbxParkLight_F, cbxHorn_F, cbxChassis_F, cbxFrontBumper_F, cbxAmpheres_F, cbxFuel_F, cbxStarter_F, cbxDifferential_F, cbxBrakes_F, cbxWiper_F, cbxBackUp_F, cbxSideMirror_F, cbxBodyFlooring_F, cbxRearBumper_F, cbxOilPressure_F, cbxSpeedometer_F, cbxBodyPaint_F, cbxEngine_P, cbxSteering_P, cbxClutch_P, cbxHeadLight_P, cbxSignalLight_P, cbxShock_P, cbxUnderchassis_P, cbxUpholstery_P, cbxTempGauge_P, cbxOdometer_P, cbxTransmission_P, cbxAcceleration_P, cbxParkLight_P, cbxHorn_P, cbxChassis_P, cbxFrontBumper_P, cbxAmpheres_P, cbxFuel_P, cbxStarter_P, cbxDifferential_P, cbxBrakes_P, cbxWiper_P, cbxBackUp_P, cbxSideMirror_P, cbxBodyFlooring_P, cbxRearBumper_P, cbxOilPressure_P, cbxSpeedometer_P, cbxBodyPaint_P})
        ReportPageInfoFontSettings({XrPageInfo1, XrPageInfo2})
    End Sub
End Class