Public Class RptCoMakersStatementCIR

    Private Sub Rpt_BeforePrint(sender As Object, e As Printing.PrintEventArgs) Handles MyBase.BeforePrint
        'USER INTERFACE
        If AllowStandardUI = False Then
            Exit Sub
        End If
        ReportLabelWithBackgroundFontSettings({XrLabel3, XrLabel56, XrLabel182, XrLabel154, XrLabel155, XrLabel156, XrLabel157, XrLabel158, XrLabel159, XrLabel160, XrLabel197, XrLabel175, XrLabel176, XrLabel177, XrLabel178, XrLabel179, XrLabel204, XrLabel248, XrLabel227, XrLabel228, XrLabel229, XrLabel233, XrLabel230, XrLabel252, XrLabel251, XrLabel250, XrLabel249})
        ReportLabelFontSettings({XrLabel1, XrLabel2, XrLabel8, XrLabel9, lblBorrower, lblAmountWords, lblAmount, XrLabel10, XrLabel4, XrLabel6, XrLabel14, XrLabel16, XrLabel18, XrLabel22, XrLabel24, XrLabel28, XrLabel33, XrLabel36, lblBorrowerID, XrLabel5, lblLoanNumber, lblComaker, lblCompleteAdd, lblProvincialAdd, lblBirthDate, XrLabel20, lblBirthPlace, XrLabel23, lblCitizenship, XrLabel26, lblTIN, lblTelephone, XrLabel30, lblSSS, lblMobile, XrLabel35, lblEmail, lblRent, XrLabel57, XrLabel63, XrLabel67, XrLabel74, XrLabel81, XrLabel85, XrLabel89, XrLabel95, lblEmployer, lblPosition, lblDateHired, lblBusiness, lblNature, lblNoEmployees, lblCoverageArea, lblOtherIncome, XrLabel59, XrLabel65, XrLabel69, XrLabel75, XrLabel79, XrLabel87, XrLabel91, XrLabel97, lblEmployerAddress, XrLabel61, lblEmployerTel, lblSupervisor, XrLabel71, lblMonthlyIncome, lblBusinessAddress, XrLabel77, lblBusinessTel, lblYearsOperation, XrLabel83, lblBusinessIncome, lblCapital, lblExpiry, XrLabel93, lblOutlet, lblOtherMonthlyIncome, lblCredit1, lblGranted1, lblTerms1, lblPrincipal1, lblOutstanding1, lblMonthlyPay1, lblCreditRemarks1, lblCredit2, lblGranted2, lblTerms2, lblPrincipal2, lblOutstanding2, lblMonthlyPay2, lblCreditRemarks2, lblBank1, lblBranch1, cbxAccountNum1, lblDaily1, lblOpened1, lblBank2, lblBranch2, cbxAccountNum2, lblDaily2, lblOpened2, XrLabel191, XrLabel202, lblRecommendation, XrLabel206, XrLabel213, XrLabel220, XrLabel225, lblTitle, lblDateFilled, lblCaseStatus, lblOtherInfo, XrLabel7, XrLabel223, lblCourtBranch, lblFindings, XrLabel217, lblCaseNature, XrLabel208, lblCaseNumber, XrLabel211, lblAmountInvolved, lblLocation1, lblTCT1, lblArea1, lblRE_Remarks1, lblLocation2, lblTCT2, lblArea2, lblRE_Remarks2, lblVehicle1, lblModel1, lblAcquired1, lblVE_Remarks1, lblVehicle2, lblModel2, lblAcquired2, lblVE_Remarks2, XrLabel253, lblOtherProperty, XrLabel256, lblNarrative, XrLabel257, XrLabel259, XrLabel261, XrLabel263, XrLabel265, XrLabel266, XrLabel268, XrLabel271, XrLabel272, XrLabel274, lblCondition1, lblCondition2, lblCondition3, lblCondition4, lblCondition5, lblCondition6, lblCondition7, lblCondition8, lblCondition9, XrLabel276, XrLabel279, XrLabel281, XrLabel283, XrLabel286, XrLabel289, XrLabel292, XrLabel295, XrLabel298, XrLabel301, XrLabel304, XrLabel307, XrLabel310, lblDateSigned_2, XrLabel133, lblSignature_3, XrLabel130, XrLabel278, lblIncome, XrLabel284, lblLivingExpense, XrLabel285, lblClothing, XrLabel290, lblEducation, XrLabel291, lblTransportation, XrLabel296, lblLight, XrLabel297, lblInsurance, XrLabel302, lblAmortazation, XrLabel303, lblMiscellaneous, XrLabel308, lblTotal, XrLabel309, lblNetDisposable, XrLabel277, XrLabel318, lblPurpose, XrLabel321, lblDeviations, XrLabel322})
        ReportCheckBoxFontSettings({cbxMale, cbxFemale, cbxSingle, cbxMarried, cbxSeparated, cbxWidowed, cbxOwned, cbxFree, cbxRented, cbxCasual, cbxTemporary, cbxPermanent, cbxSA1, cbxCA1, cbxSA2, cbxCA2, cbxGood, cbxFair, cbxPoor, cbxPositive, cbxNegative, cbxUnestablied})
        ReportPageInfoFontSettings({XrPageInfo2})
    End Sub
End Class