Public Class RptCoMakersStatement

    Private Sub Rpt_BeforePrint(sender As Object, e As Printing.PrintEventArgs) Handles MyBase.BeforePrint
        'USER INTERFACE
        If AllowStandardUI = False Then
            Exit Sub
        End If
        ReportLabelWithBackgroundFontSettings({XrLabel3, XrLabel56, XrLabel31, XrLabel100})
        ReportLabelFontSettings({XrLabel1, XrLabel2, XrLabel8, XrLabel9, lblBorrower, lblAmount, lblAmountWords, XrLabel10, XrLabel4, lblBorrowerID, XrLabel5, lblLoanNumber, lblComaker, XrLabel6, XrLabel14, lblCompleteAdd, XrLabel16, lblProvincialAdd, XrLabel18, lblBirthDate, XrLabel20, lblBirthPlace, XrLabel22, XrLabel23, XrLabel24, lblCitizenship, XrLabel26, lblTIN, XrLabel28, lblTelephone, XrLabel30, lblSSS, XrLabel33, lblMobile, XrLabel35, lblEmail, XrLabel36, lblRent, XrLabel57, lblEmployer, XrLabel59, lblEmployerAddress, XrLabel61, lblEmployerTel, XrLabel63, lblPosition, XrLabel65, XrLabel67, lblDateHired, XrLabel69, lblSupervisor, XrLabel71, lblMonthlyIncome, XrLabel74, lblBusiness, XrLabel75, lblBusinessAddress, XrLabel77, lblBusinessTel, XrLabel81, lblNature, XrLabel79, lblYearsOperation, XrLabel83, lblBusinessIncome, XrLabel85, lblNoEmployees, XrLabel87, lblCapital, XrLabel89, lblCoverageArea, XrLabel91, lblExpiry, XrLabel93, lblOutlet, XrLabel95, lblOtherIncome, XrLabel97, lblOtherMonthlyIncome, XrLabel7, lblDateSigned, lblSignature_1, lblSignature_2, XrLabel213, XrLabel210, XrLabel212, XrLabel32, lblBorrowerID_2, XrLabel46, lblLoanNumber_2, XrLabel29, lblComaker_2, XrLabel17, lblCompleteAdd_2, XrLabel19, lblProvincialAdd_2, XrLabel34, lblBirthDate_2, XrLabel52, lblBirthPlace_2, XrLabel54, XrLabel51, XrLabel70, lblCitizenship_2, XrLabel73, lblTIN_2, XrLabel58, lblTelephone_2, XrLabel62, lblSSS_2, XrLabel43, XrLabel101, lblEmployer_2, XrLabel96, lblEmployerAddress_2, XrLabel102, lblEmployerTel_2, XrLabel106, lblPosition_2, XrLabel103, XrLabel78, lblDateHired_2, XrLabel80, lblSupervisor_2, XrLabel90, lblMonthlyIncome_2, XrLabel84, lblBusiness_2, XrLabel122, lblBusinessAddress_2, XrLabel121, lblBusinessTel_2, XrLabel119, lblNature_2, XrLabel124, lblYearsOperation_2, XrLabel129, lblBusinessIncome_2, XrLabel125, lblNoEmployees_2, XrLabel118, lblCapital_2, XrLabel108, lblCoverageArea_2, XrLabel107, lblExpiry_2, XrLabel109, lblOutlet_2, XrLabel114, lblOtherIncome_2, XrLabel116, lblOtherMonthlyIncome_2, XrLabel136, lblDateSigned_2, XrLabel133, lblSignature_3, XrLabel130, lblSignature_4, XrLabel134, XrLabel215, XrLabel216})
        ReportCheckBoxFontSettings({cbxMale, cbxFemale, cbxSingle, cbxMarried, cbxSeparated, cbxWidowed, cbxOwned, cbxFree, cbxRented, cbxCasual, cbxTemporary, cbxPermanent, cbxMale_2, cbxFemale_2, cbxSingle_2, cbxMarried_2, cbxSeparated_2, cbxWidowed_2, cbxOwned_2, cbxFree, cbxRented_2, cbxCasual_2, cbxTemporary_2, cbxPermanent_2})
        ReportPageInfoFontSettings({XrPageInfo2})
    End Sub
End Class